on: [push,pull_request]

name: bridgecrew Action
jobs:
  bridgecrew-check:
    name: bridgecrew check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Bridgecrew
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
          api-key: ${{ secrets.BC_API_KEY }}
